const ACTIONS = {
  SEARCH_START: 'SEARCH_START',
  SEARCH_ERROR: 'SEARCH_ERROR',
  SEARCH_END: 'SEARCH_END',
  SEARCH_USER_DATA_ERROR: 'SEARCH_USER_DATA_ERROR',
  RESET_SEARCH: 'RESET_SEARCH',
  CHANGE_SEARCH_TERM: 'CHANGE_SEARCH_TERM',
  CHANGE_PAGE: 'CHANGE_PAGE'
};

export default ACTIONS;
